package cache_v2

import (
	"crypto/x509"
	"encoding/pem"
	"errors"
	"io/fs"
	"log"
	"math/big"
	"math/rand"
	"os"
	"testing"
	"time"
)

func TestMain(m *testing.M) {
	regenerated, err := regenerateTestRootCertificateIfNecessary()
	if err != nil {
		log.Fatalf("Failed to regenerate root certificate: %v", err)
	}
	if regenerated {
		log.Fatal("Root certificate regenerated and added to embedded filesystem and will be available on the next test run")
	}

	m.Run()
}

// Regenerates the root certificate used in unit tests if it does not exist or is expired, returns true if the certificate has been regenerated by this function or another concurrent execution of this function
func regenerateTestRootCertificateIfNecessary() (bool, error) {
	// code to generate root in case root certificate for testing expires
	var regenerateRootCertificate bool
	pemBytes, err := cacheFileSystem.ReadFile("embedded/unit_test/cache/root_certificates/root_certificate.pem")
	if errors.Is(err, fs.ErrNotExist) {
		log.Println("Root certificate does not exist")
		regenerateRootCertificate = true
	} else if err == nil {
		pemBlock, _ := pem.Decode(pemBytes)
		certificate, err := x509.ParseCertificate(pemBlock.Bytes)
		if err != nil {
			return false, err
		}

		// if the root certificate has expired or expires in less than 1 hour
		minDelta, err := time.ParseDuration("1h")
		if err != nil {
			return false, err
		}
		if certificate.NotAfter.Sub(time.Now()) < minDelta {
			regenerateRootCertificate = true
			log.Println("Existing root certificate is (almost) expired")
		}
	} else {
		return false, err
	}

	if regenerateRootCertificate {
		// generate new root certificate
		log.Println("Regenerating root certificate ...")

		privateKey, err := CreateAndStoreRSAPrivateKey(rand.New(rand.NewSource(int64(0))))
		if err != nil {
			return false, err
		}

		privateKeyBytes := x509.MarshalPKCS1PrivateKey(privateKey)
		p := EncodePEM(privateKeyBytes, "PRIVATE KEY")
		err = os.WriteFile("embedded/unit_test/cache/root_privatekeys/root_privatekey.pem", p, 0777)
		if err != nil {
			return false, err
		}

		template, err := CreateCertificateTemplate(big.NewInt(int64(0)), []string{"root"}, 1, 1, 1, 1, true, nil, x509.SHA256WithRSA)
		if err != nil {
			return false, err
		}

		pemBytes, err := CreateCertificate(template, privateKey.Public(), template, privateKey, rand.New(rand.NewSource(int64(0))))
		if err != nil {
			return false, err
		}

		err = os.WriteFile("embedded/unit_test/cache/root_certificates/root_certificate.pem", pemBytes, 0777)
		if err != nil {
			return false, err
		}

		log.Println("Root certificate (re-)generated, please rerun the test")
	}
	return regenerateRootCertificate, nil
}
