package cache_v2

import (
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"math/big"
	"math/rand"
	"os"
	"testing"
	"time"

	"github.com/netsec-ethz/fpki/pkg/common"
	"github.com/netsec-ethz/fpki/pkg/common/crypto"
	"github.com/netsec-ethz/fpki/pkg/util"
)

func TestMain(m *testing.M) {
	rootCertRegenerated, err := regenerateTestRootCertificateIfNecessary()
	if err != nil {
		log.Fatalf("Failed to regenerate root certificate: %v", err)
	}
	if rootCertRegenerated {
		log.Println("Root certificate regenerated and added to embedded filesystem and will be available on the next test run")
	}

	pcaRegenerated, err := regenerateTestPcaCertificateIfNecessary()
	if err != nil {
		log.Fatalf("Failed to regenerate PCA certificate: %v", err)
	}
	if pcaRegenerated {
		log.Println("PCA regenerated and added to embedded filesystem and will be available on the next test run")
	}

	if rootCertRegenerated || pcaRegenerated {
		log.Fatal("Please rerun the tests")
	}

	m.Run()
}

func regenerateTestPcaCertificateIfNecessary() (bool, error) {
	// code to generate the test PCA certificate in case root it expires
	var regenerateRootCertificate bool
	cert, err := common.JsonFileToPolicyCert("embedded/unit_test/policy_cache/root_certificates/root_certificate_0.pc")
	if err != nil {
		log.Println("PCA certificate does not exist or is malformed")
		regenerateRootCertificate = true
	} else {
		now := time.Now()
		if !(cert.NotBefore.Before(now) && now.Before(cert.NotAfter.AddDate(0, 0, -1))) {
			log.Println("Existing PCA certificate is (almost) expired")
			regenerateRootCertificate = true
		}
	}

	if regenerateRootCertificate {
		// generate new PCA certificate
		log.Println("Regenerating PCA certificate ...")

		err = os.MkdirAll("embedded/unit_test/policy_cache/root_privatekeys", 0777)
		if err != nil {
			return false, err
		}
		err = os.MkdirAll("embedded/unit_test/policy_cache/root_certificates", 0777)
		if err != nil {
			return false, err
		}

		for i := 0; i < 3; i++ {
			err = generatePca(int64(i), "")
			if err != nil {
				return false, err
			}
		}

		log.Println("PCA certificate (re-)generated")
	}
	return regenerateRootCertificate, nil
}

func generatePca(pcaId int64, domain string) error {
	privateKey, err := CreateAndStoreRSAPrivateKey(rand.New(rand.NewSource(pcaId)))
	if err != nil {
		return err
	}

	privateKeyBytes := x509.MarshalPKCS1PrivateKey(privateKey)
	p := EncodePEM(privateKeyBytes, "PRIVATE KEY")
	err = os.WriteFile(fmt.Sprintf("embedded/unit_test/policy_cache/root_privatekeys/root_privatekey_%d.pem", pcaId), p, 0777)
	if err != nil {
		return err
	}

	// create certificate signing request
	now := time.Now()
	notBefore := now.AddDate(-1, 0, 0)
	notAfter := now.AddDate(1, 0, 0)

	// convert the public key to byte form
	publicKeyBytes, err := util.RSAPublicToDERBytes(&privateKey.PublicKey)
	if err != nil {
		return err
	}

	cert := common.NewPolicyCertificate(0, 0, domain, notBefore, notAfter, true, false, publicKeyBytes, common.RSA, common.SHA256, time.Now(), common.PolicyAttributes{}, nil, nil, nil, nil, nil)

	// create a self-signed certificate
	err = crypto.SignPolicyCertificateAsIssuer(cert, privateKey, cert)
	if err != nil {
		return err
	}

	// set the issuer hash to nil to indicate a self-signed certificate
	cert.IssuerHash = nil

	// write it to the embedded file system
	err = common.ToJSONFile(cert, fmt.Sprintf("embedded/unit_test/policy_cache/root_certificates/root_certificate_%d.pc", pcaId))
	if err != nil {
		return err
	}
	return nil
}

// Regenerates the root certificate used in unit tests if it does not exist or is expired, returns true if the certificate has been regenerated by this function or another concurrent execution of this function
func regenerateTestRootCertificateIfNecessary() (bool, error) {
	// code to generate root in case root certificate for testing expires
	var regenerateRootCertificate bool
	pemBytes, err := cacheFileSystem.ReadFile("embedded/unit_test/cache/root_certificates/root_certificate.pem")
	if errors.Is(err, fs.ErrNotExist) {
		log.Println("Root certificate does not exist")
		regenerateRootCertificate = true
	} else if err == nil {
		pemBlock, _ := pem.Decode(pemBytes)
		certificate, err := x509.ParseCertificate(pemBlock.Bytes)
		if err != nil {
			return false, err
		}

		// if the root certificate has expired or expires in less than 1 hour
		minDelta, err := time.ParseDuration("1h")
		if err != nil {
			return false, err
		}
		if certificate.NotAfter.Sub(time.Now()) < minDelta {
			regenerateRootCertificate = true
			log.Println("Existing root certificate is (almost) expired")
		}
	} else {
		return false, err
	}

	if regenerateRootCertificate {
		// generate new root certificate
		log.Println("Regenerating root certificate ...")

		err = os.MkdirAll("embedded/unit_test/cache/root_privatekeys", 0777)
		if err != nil {
			return false, err
		}
		err = os.MkdirAll("embedded/unit_test/cache/root_certificates", 0777)
		if err != nil {
			return false, err
		}

		privateKey, err := CreateAndStoreRSAPrivateKey(rand.New(rand.NewSource(int64(0))))
		if err != nil {
			return false, err
		}

		privateKeyBytes := x509.MarshalPKCS1PrivateKey(privateKey)
		p := EncodePEM(privateKeyBytes, "PRIVATE KEY")
		err = os.WriteFile("embedded/unit_test/cache/root_privatekeys/root_privatekey.pem", p, 0777)
		if err != nil {
			return false, err
		}

		template, err := CreateCertificateTemplate(big.NewInt(int64(0)), []string{"root"}, 1, 1, 1, 1, true, nil, x509.SHA256WithRSA)
		if err != nil {
			return false, err
		}

		pemBytes, err := CreateCertificate(template, privateKey.Public(), template, privateKey, rand.New(rand.NewSource(int64(0))))
		if err != nil {
			return false, err
		}

		err = os.WriteFile("embedded/unit_test/cache/root_certificates/root_certificate.pem", pemBytes, 0777)
		if err != nil {
			return false, err
		}

		log.Println("Root certificate (re-)generated")
	}
	return regenerateRootCertificate, nil
}
