version: '3'
services:
  lfpki-plugin-db:
    image: mysql:8
    command: --max_allowed_packet=1073741824 --max_connections=10000
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: zaphod
    container_name: lfpki-plugin-db
    ports:
      - "3307:3306"
    tty: true
